### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DDimitris** [circuit/imdb-collaboration#1]
The [imdb example link](https://imdb.circuitsandbox.net/) doesn't work. It produces a ```ERR_TUNNEL_CONNECTION_FAILED``` error.

**Comment by rogeru** [comment]
Thanks for the info. We are in the process of moving our example to Google Cloud. Should be back up in the next days.

**Comment by DDimitris** [comment]
Awesome!! :) :)

**Comment by rogeru** [comment]
https://imdb.circuit-apps.com/
